-- DAO에 쓸 QUERY
-- 1번기능과 2번 기능에서 입력가능한 직업명들
SELECT JNAME FROM JOB;

-- 1번 기능 : PNAME, JNAME, KOR, ENG, MAT를 입력받아 PERSON 테이블 INSERT
INSERT INTO PERSON (PNO, PNAME, JNO, KOR, ENG, MAT)
  VALUES (PERSON_PNO_SQ.NEXTVAL, '홍길동',
    (SELECT JNO FROM JOB WHERE JNAME='배우'),
    90,95,99);