# Generated by Django 5.1.6 on 2025-02-25 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.CharField(
                max_length=50,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name="저자",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="publisher",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="출판사"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="sales",
            field=models.IntegerField(
                default=1000,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000000),
                ],
                verbose_name="판매가",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=50, verbose_name="책제목"),
        ),
    ]
