-- [VIII] Sequence : 순차번호 생성기. 인위적인 PK 사용 용도
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH 1 -- 1부터 시작(기본값)
    INCREMENT BY 1 -- 1씩 증가(기본값)
    MAXVALUE 9999 -- 최대값
    MINVALUE 1    -- 최소값
    NOCACHE
    NOCYCLE;
SELECT FRIEND_SEQ.NEXTVAL FROM DUAL; -- 다음 순차번호 생성
SELECT FRIEND_SEQ.CURRVAL FROM DUAL; -- 시퀀스의 현재 값
-- ex1. FRIEND테이블(NO1,2,3-PK, NAME, TEL, ADDDRESS, LAST_MODIFY)
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ MAXVALUE 99999 NOCACHE NOCYCLE;
DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NO      NUMBER(5) PRIMARY KEY,
    NAME    VARCHAR2(30) NOT NULL,
    TEL     VARCHAR2(20) UNIQUE, -- NULL허용. NULL이 아닐 때는 유일한 값
    ADDRESS VARCHAR2(255),
    LAST_MODIFY DATE DEFAULT SYSDATE
);
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', NULL, '서울시 관악구'); -- 3번 실행 가능
SELECT * FROM FRIEND;
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, NULL, '010-9999-9999','서울'); -- 에러(NOT NULL)
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, '박길동', '010-9999-9999','서울');
SELECT * FROM FRIEND;

-- ex2. FRIEND테이블(NO20240924001, 날짜002-PK, NAME, TEL, ADDDRESS, LAST_MODIFY)
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ MAXVALUE 999 NOCACHE NOCYCLE;
DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NO      NUMBER(11) PRIMARY KEY,
    NAME    VARCHAR2(30) NOT NULL,
    TEL     VARCHAR2(20) UNIQUE, -- NULL허용. NULL이 아닐 때는 유일한 값
    ADDRESS VARCHAR2(255),
    LAST_MODIFY DATE DEFAULT SYSDATE
);
SELECT TO_CHAR(SYSDATE, 'YYYYMMDD')||TRIM(TO_CHAR(33, '000')) FROM DUAL;
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES (TO_CHAR(SYSDATE, 'YYYYMMDD') ||TRIM(TO_CHAR(FRIEND_SEQ.NEXTVAL, '000')), 
            '홍길동', NULL, '서울시 관악구'); 
SELECT * FROM FRIEND;

-- QUIZ
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;
DROP SEQUENCE MEMBER_MNO_SQ;
