-- [X] VIEW, IN-LINE VIEW, ★TOP-N★
-- 1. VIEW : 가상의 테이블 (1)단순뷰 (2)복합뷰
-- (1)단순뷰 : 하나의 테이블을 이용해서 만든 뷰(가상의 테이블은 물리공간과 데이터가 따로 없음)
CREATE OR REPLACE VIEW EMPv0 -- EMP테이블에서 특정 필드만 VIEW로 생성
    AS SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, DEPTNO FROM EMP;
SELECT * FROM EMP;
SELECT * FROM EMPv0;
SELECT * FROM TAB; -- 내 계정이 갖고 있는 테이블들(가상의 테이블 포함)
SELECT * FROM USER_TABLES; -- 내 계정이 갖고 있는 테이블(가상의 테이블 미포함)
SELECT * FROM USER_VIEWS;
INSERT INTO EMPv0 VALUES (1111, '홍', 'MANAGER', NULL, NULL, 40); -- 뷰에 INSERT
SELECT * FROM EMPv0;
SELECT * FROM EMP;
ROLLBACK;

CREATE OR REPLACE VIEW EMPv0 -- EMP테이블에서 특정 행(ROW)만 VIEW로 생성
    AS SELECT * FROM EMP WHERE DEPTNO=30;
SELECT * FROM EMPv0;
INSERT INTO EMPv0 VALUES (1111, '홍', 'MANAGER', NULL, NULL, 9000, NULL, 40); -- 가능
SELECT * FROM EMPv0; -- 1111번 사원 안 보임
SELECT * FROM EMP; -- 1111번 사원 보임
--단순뷰에서 INSERT가 불가한 경우 : 뷰 생성시 NOT NULL 필드를 미포함한 경우 
CREATE OR REPLACE VIEW EMPv0
    AS SELECT ENAME, JOB FROM EMP;
SELECT * FROM EMPv0;
INSERT INTO EMPv0 VALUES ('홍', 'MANAGER');
DELETE FROM EMP WHERE EMPNO=1111;

-- VIEW의 제한 조건
-- WITH CHECK OPTION 추가 : 뷰의 조건에 해당되는 데이터만 삽입, 수정, 삭제가 가능
-- WITH READ ONLY 추가 : 읽기 전용 뷰
CREATE OR REPLACE VIEW EMPv0
    AS SELECT * FROM EMP WHERE DEPTNO=30
    WITH CHECK OPTION;
SELECT * FROM EMPv0 E, DEPT D WHERE E.DEPTNO=D.DEPTNO;
INSERT INTO EMPv0 (EMPNO, ENAME, DEPTNO) VALUES (1111, '홍', 30); -- 가능
INSERT INTO EMPv0 (EMPNO, ENAME, DEPTNO) VALUES (1112, '박', 40); -- VIEW 제한조건으로 에러
SELECT * FROM EMP WHERE ENAME='SMITH';
DELETE FROM EMPv0 WHERE ENAME='SMITH'; -- VIEW 제한조건에 맞지 않은 데이터는 DELETE 안 됨
SELECT * FROM EMP WHERE ENAME='홍';
DELETE FROM EMPv0 WHERE ENAME='홍';
COMMIT;

-- 읽기 전용 단순뷰(WITH READ ONLY 추가)
CREATE OR REPLACE VIEW EMPv0
    AS SELECT * FROM EMP WHERE DEPTNO=20 WITH READ ONLY; 
INSERT INTO EMPv0 (EMPNO, ENAME, DEPTNO) VALUES (1111, '홍', 20); -- READ ONLY 에러

-- (2)복합뷰 : 2개 이상의 테이블로 구성한 뷰, 가상의 필드를 이용한 뷰. DML문을 제한적으로만 이용(SELECT)
-- ① 2개 이상의 테이블로 구성한 복합뷰
CREATE OR REPLACE VIEW EMPv0
    AS SELECT EMPNO, ENAME, JOB, DNAME FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO;
SELECT * FROM EMPv0;
INSERT INTO EMPv0 VALUES (1111, '홍','MANAGER', 'SALES'); -- 에러
-- ② 가상의 필드를 이용한 복합뷰(컬럼에 별칭을 사용)
CREATE OR REPLACE VIEW EMPv0
    AS SELECT EMPNO, ENAME, SAL*12 YEAR_SAL FROM EMP WHERE DEPTNO=10; -- 별칭을 필드
CREATE OR REPLACE VIEW EMPv0 (NO, NAME, YEAR_SAL) -- 별칭들만 따로 
    AS SELECT EMPNO, ENAME, SAL*12 FROM EMP WHERE DEPTNO=10;
SELECT * FROM EMPv0;
INSERT INTO EMPv0 VALUES (1111, 'LEE', 1200); -- 복합뷰는 INSERT 불가





