-- 친구 데이터 저장할 table 생성
DROP TABLE FRIEND;
DROP SEQUENCE FRIEND_NO_SQ;
CREATE TABLE FRIEND(
  NO NUMBER(4) PRIMARY KEY,
  NAME VARCHAR2(50) NOT NULL,
  TEL  VARCHAR2(30) UNIQUE
);
CREATE SEQUENCE FRIEND_NO_SQ MAXVALUE 9999 NOCACHE NOCYCLE;
-- 더미 데이터 insert

-- DAO에 들어갈 query