# Generated by Django 5.1.6 on 2025-02-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="region",
            field=models.CharField(
                choices=[
                    ("Europe", "유럽"),
                    ("Asia", "아시아"),
                    ("Africa", "아프리카"),
                    ("Oceania", "오세아니아"),
                    ("America", "아메리카"),
                ],
                default="Asia",
                max_length=20,
            ),
        ),
    ]
