# Generated by Django 5.1.6 on 2025-02-27 11:13

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="기사제목")),
                ("body", models.TextField(verbose_name="기사본문")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("d", "Draft"),
                            ("p", "Published"),
                            ("w", "Withdrawn"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to=article.models.article_photo_path
                    ),
                ),
            ],
        ),
    ]
